using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Main : MonoBehaviour
{
    static public Main Instance;

    public int switchCount;
    public GameObject winText;
    private int onCount = 0;

    private void Awake()
    {
        Instance = this;
    }

    public void SwitchChange(int points)
    {
        onCount = onCount + points;
        if (onCount == switchCount)
        {
            winText.SetActive(true);

            // NOVO: avisa ao GameManager que a tarefa foi concluída
            GameManager.Instance.wireTaskCompleted = true;

            // NOVO: volta para a cena do parque (ajuste o nome se for diferente)
            SceneManager.LoadScene("Jogo");
        }
    }

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.R))
        {
            SceneManager.LoadScene(SceneManager.GetActiveScene().name);
        }
    }
}
